apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggereditor
  namespace: prac05
  labels:
   app: swaggereditor
spec:
 replicas: 1
 selector:
   matchLabels:
     app: swaggereditor
 template:
   metadata:
     labels:
       app: swaggereditor
   spec:
     containers:
     - name: swaggereditor
       image: swaggerapi/swagger-editor
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-swaggereditor
  namespace: prac05
spec:
  type: NodePort
  selector:
    app: swaggereditor
  ports:
  - protocol: TCP
    port: 8080 # internal cluster port
    targetPort: 8080 # Port your application listen on in pods/containers
    name: tcp-8080
