---
- name: create
  hosts: k3s_controller
  gather_facts: true
  become: true
  become_user: ubuntu

  tasks:
    - name: Delete the flask ms deployment
      command: "k3s kubectl delete -f /home/ubuntu/prac05/prac05-flask_microservice/flask-ms-deployment.yaml"
      register: delete_out    
    - debug:
       msg: "output of delete_out command: {{delete_out.stdout_lines}}"
    - name: Create the flask ms deployment
      command: "k3s kubectl apply -f /home/ubuntu/prac05/prac05-flask_microservice/flask-ms-deployment.yaml"
      register: create_out    
    - debug:
       msg: "output of create_out command: {{create_out.stdout_lines}}"
