apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
  labels:
   app: myfirst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirst
  template:
    metadata:
      labels:
        app: myfirst
    spec:
     containers:
     - name: mynginx
       image: nginx
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-myfirst
spec:
  type: NodePort
  selector:
    app: myfirst
  ports:
  - protocol: TCP
    port: 80 #internal cluster port
    targetPort: 80 #Port your app listens on in pods/containers
    name: tcp-80
