apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
  namespace: ex3
  labels:
   app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
     containers:
     - name: flask
       image: widyrob/devops2024:prac2
       ports:
       - containerPort: 5000
       env:
       - name: INFLUX_HOST_ADD
         valueFrom:
           configMapKeyRef:
             name: studhost
             key: host
       - name: INFLUX_ORG
         value: "UT"
       - name: INFLUX_TOKEN
         valueFrom:
           secretKeyRef:
             name: influx
             key: token
---
apiVersion: v1
kind: Service
metadata:
  name: service-flaskapp
  namespace: ex3
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000 #internal cluster port
    targetPort: 5001 #Port your app listens on in pods/containers
    name: tcp-80
