---
- name: create
  hosts: k3s_controller
  gather_facts: true
  # become: true
  become_user: ubuntu


  tasks:


    #- name: create a namespace monitoring
      #command: "k3s kubectl create namespace monitoring"
     


    - name: Install prometheus
      command: "k3s kubectl apply  -f prometheus/"


    - name: Install alertmanager
      command: "k3s kubectl apply  -f alertmanager/"


    - name: Install kube-state-metrics
      command: "k3s kubectl apply  -f kube-state-metrics/"


    - name: Install node-exporter
      command: "k3s kubectl apply  -f node-exporter/"
