apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskmicroservice
  namespace: prac05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskmicroservice
  template:
    metadata:
      labels:
        app: flaskmicroservice
    spec:
      containers:
      - name: flaskmicroservice
        image: widyrob/devops2024:prac5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: STUD_INFLUX_HOST_ADD
          valueFrom:
            configMapKeyRef:
              name: studhost
              key: host
        - name: STUD_INFLUX_ORG
          value: "UT"
        - name: STUD_INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: influx
              key: token
---
apiVersion: v1
kind: Service
metadata:
  name: service-flaskmicroservice
  namespace: prac05
spec:
  type: NodePort
  selector:
    app: flaskmicroservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30086
    name: tcp-8080
