apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvolume-prac05
  namespace: prac05
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-prac05"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: In
          values:
          - k3snode1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-pvc-prac05
  namespace: prac05
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: prac05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:2
        imagePullPolicy: Always
        name: influxdb
        ports:
           - containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb2
          name: var-lib-influxdb
      volumes:
      - name: var-lib-influxdb
        persistentVolumeClaim:
          claimName: influxdb-pvc-prac05
---
apiVersion: v1
kind: Service
metadata:
  name: service-influxdb
  namespace: prac05
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086 # internal cluster port
    targetPort: 8086 # Port your application listen on in pods/containers
    name: tcp-8086
