---
- name: create
  hosts: k3s_controller
  #gather_facts: true
  #become: true
  #become_user: ubuntu

  tasks:
    - name: Delete the flask deployment
      command: "k3s kubectl delete -f flask-deployment.yaml --kubeconfig /home/gitlab-runner/.kube/config"
      register: delete_out    
    - debug:
       msg: "output of delete_out command: {{delete_out.stdout_lines}}"
    - name: Create the flask deployment
      command: "k3s kubectl apply -f flask-deployment.yaml --kubeconfig /home/gitlab-runner/.kube/config"
      register: create_out    
    - debug:
       msg: "output of create_out command: {{create_out.stdout_lines}}"
